---
title: "Midterm 2 - Stat 153"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(aTSA)
library(astsa)
library(forecast)
```

```{r}
dat1 <- read.csv("data1.csv")
dat2 <- read.csv("data2.csv")
dat3 <- read.csv("data3.csv")
plot(dat1, type = 'l')
plot(dat2, type = 'l')
plot(dat3, type = 'l')
```
```{r}
acf(dat1$x, lag.max=300)
dat1_test <- diff(dat1$x, differences = 1)


plot(dat1_test, type = 'l')
lines(lm(dat1_test~I(1:length(dat1_test)))$fitted)
plot(lm(dat1_test~I(1:length(dat1_test)))$resid)

acf(dat1_test, lag.max=300)
pacf(dat1_test, lag.max=300)

auto.arima(dat1$x,d=1,max.order = 14, stepwise = FALSE, approximation = FALSE)

sarima(dat1$x, 2,1,2)


```

```{r}
model1 <- Arima(dat1$x, order = c(2,1,2), method = 'CSS')
model1

predictions1 = predict(model1, n.ahead=10)
plot(dat1, xlim = c(0,510), type = 'l', main = "Next 10 Predictions")
lines(predictions1$pred, col='blue')
predictions1$pred
```




```{r}
dat2_test <- diff(dat2$x, differences = 1)
dat2_test <- diff(dat2_test, lag =12)

plot(dat2_test)
lines(lm(dat2_test~I(1:length(dat2_test)))$fitted)
acf(dat2_test, lag.max = 300)
pacf(dat2_test, lag.max = 300)

acf(dat2_test)
pacf(dat2_test)

dat2_main <- ts(dat2$x, frequency = 12)
plot(dat2_main)
```

```{r}
auto.arima(dat2_main,d=1,D=1,max.order = 7, trace = TRUE, stepwise = FALSE, approximation = FALSE)
```

```{r}
sarima(dat2$x, 1,1,1,0,1,1,12)
```
```{r}
model2 <- Arima(dat2$x, order = c(1,1,1), seasonal = list(order = c(0,1,1), period = 12), method = 'CSS')
model2

predictions2 = predict(model2, n.ahead=10)
plot(dat2, xlim = c(0,510), type = 'l', main = "Next 10 Predictions")
lines(predictions2$pred, col='blue')
predictions2$pred
```

```{r}
acf3 <- acf(dat3$x, lag.max = 200)
which.max(acf3$acf[150:200])
pacf(dat3$x, lag.max =200)
dat3_test <- diff(dat3$x,differences = 1)
plot(dat3_test, type = 'l')
acf(dat3_test, lag.max = 200)
pacf(dat3_test, lag.max = 200)

dat3_main <- ts(dat3$x, frequency = 159)
```

```{r}
dat3_test <- diff(dat3$x, lag = 159, differences = 1)
dat3_test <- diff(dat3_test)
plot(dat3_test, type = 'l')
lines(lm(dat3_test~I(1:length(dat3_test)))$fitted)
pacf(dat3_test)
acf(dat3_test)
pacf(dat3_test, lag.max = 340)
acf(dat3_test, lag.max = 340)
```
```{r}
auto.arima(dat3$x, approximation = FALSE, stepwise = FALSE, d=1, max.order = 14, allowmean = FALSE)
auto.arima(dat3_main, D=1, max.order = 5, allowmean = FALSE, trace = TRUE, allowdrift = FALSE)
auto.arima(dat3_main, d=1, D=1, max.order = 5, ic = "bic", trace = TRUE, allowdrift = FALSE)
#auto.arima(dat3$x, approximation = FALSE, stepwise = FALSE, d=1, D=1, max.order = 14, ic = "aic")
#auto.arima(dat3$x, approximation = FALSE, stepwise = FALSE, d=1, D=1, max.order = 14, ic = "aicc")
```

```{r}
sarima(dat3$x, 1,0,0,0,1,0,159)
sarima(dat3$x, 2,1,1,0,1,0,159)
```

```{r}
model3 <- Arima(dat3$x, order = c(2,0,0), seasonal = list(order = c(0,1,0), period = 159))
predictions = predict(model3, n.ahead=10)
plot(dat3, xlim = c(0,510), type = 'l')
lines(predictions$pred, col='blue')
```

